# En este archivo se encuentra la configuraci贸n del despliegue de la aplicaci贸n
# utilizando Kubernetes (K8s es su acronimo, lo vamos a usar para referirnos asi mas adelante).
# En cada punto especificaremos los elementos respectivos.

# Version del API de Kubernetes
apiVersion: apps/v1
# Tipo de elemento
kind: Deployment
# Metadatos del elemento
metadata:
  # Nombre
  name: inquilinos
  # Etiqueta del Deployment
  labels:
    app: inquilinos
# Especificaciones del elemento
spec:
  replicas: 1
  # K8s agrupa los elementos del Deployment y los interconecta entre si utilizando etiquetas
  # Aqui definimos como seleccionar los elementos juntos
  selector:
    # En este caso va a seleccionar aquellos que coincidan con el nombre del deploy
    matchLabels:
      app: inquilinos
  # En esta secci贸n definimos el contenido del pod y declaramos los contenedores
  template:
    metadata:
      labels:
        # Esta es la etiqueta que se le asigna al pod, debe ser igual al selector (linea 24)
        app: inquilinos
    spec:
      # Declaracion de contenedores
      # name: Nombre del contenedor
      # image: Nombre de la imagen, por defecto buscara en Docker Hub o en el repositorio privado
      #        configurado en K8s
      containers:
        - name: inquilinos
          image: us-east4-docker.pkg.dev/nomonoliticas/nomonolitcas/inquilinos/flask:latest
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 5000
          # Realizar pull siempre a la imagen
          imagePullPolicy: Always

        - name: dbinquilinos
          image: us-east4-docker.pkg.dev/nomonoliticas/nomonolitcas/db_inquilinos:latest
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 3308
          # Realizar pull siempre a la imagen
          imagePullPolicy: Always

        - name: pulsarbookie
          image: us-east4-docker.pkg.dev/nomonoliticas/nomonolitcas/bookie:latest
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 3181
          # Realizar pull siempre a la imagen
          imagePullPolicy: Always

        - name: pulsarbroker
          image: us-east4-docker.pkg.dev/nomonoliticas/nomonolitcas/broker:latest
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 6650
          # Realizar pull siempre a la imagen
          imagePullPolicy: Always

        - name: pulsarinit
          image: us-east4-docker.pkg.dev/nomonoliticas/nomonolitcas/pulsar-init:latest
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 6650
          # Realizar pull siempre a la imagen
          imagePullPolicy: Always

        - name: zookeper
          image: us-east4-docker.pkg.dev/nomonoliticas/nomonolitcas/zookeper:latest
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 2181
          # Realizar pull siempre a la imagen
          imagePullPolicy: Always   

# Vamos a especificar el balanceador de carga en este mismo archivo
# para ello vamos a crear otro documento separado, esto se hace con el operador "---"
---
kind: Service
apiVersion: v1
metadata:
  name: servicio-inquilinos
spec:
  type: LoadBalancer
  selector:
    app: inquilinos
  # Declaracion y redireccion del trafico por los puertos
  # En este caso, estamos ocupando el puerto 80 para la conexi贸n HTTP
  # y lo estamos redirigiendo al 3000 de la red virtual del pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000